package engine

// phase5_integration_test.go — end-to-end tests for the Phase 5 REAL
// native generation: the complete production boundary
//
//      Go (this test) → IPC generate op → shtn-engine-host generation
//      lane → C++ engine (tokenizer → transformer forward pass →
//      sampler over REAL logits → fp16 KV cache → repeated decode) →
//      streamed event frames → Go stream callback → final metrics.
//
// The fixtures come from native/engine/tests/fixtures (generated by
// tests/reference/make_fixture.py — the same files the C++ reference
// comparison uses):
//   - tiny-llama-f32.gguf  the model whose logits were verified against
//                          the independent Python reference;
//   - tiny-llama-slow.gguf bigger dims so one token takes milliseconds
//                          (deterministic cancellation windows).
//
// Skips when the C++ host binary is not built (same policy as the other
// real-host tests). These tests do NOT fake anything: the text, metrics,
// KV accounting and scheduler counts are all measured by the real
// engine.

import (
	"context"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/Parsaetak/SHEYTAN-local-agent/internal/llm"
)

// nativeFixturePath resolves a fixture relative to the repository's
// native/engine/tests/fixtures directory.
func nativeFixturePath(name string) string {
	return realHostBinaryPathUp(3) + "/tests/fixtures/" + name
}

// realHostBinaryPathUp walks up from this package's directory.
func realHostBinaryPathUp(levels int) string {
	// realHostBinaryPath() computes <repo>/native/engine/build; the
	// fixtures live at <repo>/native/engine/tests/fixtures.
	bin := realHostBinaryPath()
	idx := strings.LastIndex(bin, "/build")
	if idx > 0 {
		return bin[:idx]
	}
	return bin
}

// startRealHost boots the REAL C++ host binary and returns the engine.
func startRealHost(t *testing.T) *Engine {
	t.Helper()

	bin := realHostBinaryPath()
	if !fileExists(bin) {
		t.Skipf("C++ host binary not built (%s); build native/engine with CMake to enable", bin)
	}

	e := New(bin)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := e.Start(ctx); err != nil {
		t.Fatalf("start real host: %v", err)
	}

	t.Cleanup(func() {
		stopCtx, stopCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer stopCancel()
		_ = e.Stop(stopCtx)
	})

	return e
}

// loadRealFixture loads one of the fixture models on the engine.
func loadRealFixture(t *testing.T, e *Engine, name string) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	path := nativeFixturePath(name)
	if !fileExists(path) {
		t.Fatalf("fixture missing: %s (regenerate: python3 native/engine/tests/reference/make_fixture.py)", path)
	}

	if err := e.LoadModel(ctx, ModelSpec{Path: path}); err != nil {
		t.Fatalf("load fixture %s: %v", name, err)
	}
}

// TestRealCppHostPhase5EndToEndGeneration is the Phase 5 acceptance
// test: load the REAL fixture model → native generation through the
// complete Go↔C++ boundary → streamed chunks → decoded text → measured
// metrics → honest KV accounting.
func TestRealCppHostPhase5EndToEndGeneration(t *testing.T) {
	e := startRealHost(t)
	loadRealFixture(t, e, "tiny-llama-f32.gguf")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// The capability verdict must be live before generation.
	if !e.NativeGenerationCapable() {
		t.Fatal("real fixture must report generation capable")
	}

	var mu sync.Mutex
	var text strings.Builder
	var chunkCount int

	result, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "e2e-1",
		Prompt:    "hello",
		MaxTokens: 8,
	}, func(chunk GenerationChunk) error {
		mu.Lock()
		defer mu.Unlock()
		chunkCount++
		text.WriteString(chunk.Text)
		return nil
	})
	if err != nil {
		t.Fatalf("native generation: %v", err)
	}

	if result.FinishReason != FinishLength {
		t.Fatalf("finish reason = %q, want length", result.FinishReason)
	}
	if result.GeneratedTokens != 8 {
		t.Fatalf("generated tokens = %d, want 8", result.GeneratedTokens)
	}
	if result.PromptTokens != 5 {
		t.Fatalf("prompt tokens = %d, want 5 (BOS + ▁ + he + ll + o)", result.PromptTokens)
	}

	// MEASURED metrics (monotonic clock; never fabricated).
	if result.Metrics.TTFTSeconds <= 0 {
		t.Fatalf("TTFT not measured: %+v", result.Metrics)
	}
	if result.Metrics.TotalSeconds < result.Metrics.TTFTSeconds {
		t.Fatalf("total (%f) < TTFT (%f)", result.Metrics.TotalSeconds, result.Metrics.TTFTSeconds)
	}
	if result.Metrics.TokensPerSecond <= 0 {
		t.Fatalf("tokens/sec not measured: %+v", result.Metrics)
	}
	if result.Metrics.KVPositionsUsed != 12 { // 5 prompt + 7 fed back
		t.Fatalf("kv positions used = %d, want 12", result.Metrics.KVPositionsUsed)
	}

	if chunkCount < 1 {
		t.Fatalf("no streamed chunks received")
	}
	if text.Len() == 0 {
		t.Fatal("no generated text")
	}

	// Deterministic greedy continuation: same request → same text.
	var text2 strings.Builder
	result2, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "e2e-2",
		Prompt:    "hello",
		MaxTokens: 8,
	}, func(chunk GenerationChunk) error {
		text2.WriteString(chunk.Text)
		return nil
	})
	if err != nil {
		t.Fatalf("second native generation: %v", err)
	}
	if text2.String() != text.String() {
		t.Fatalf("greedy generation is not deterministic: %q vs %q", text2.String(), text.String())
	}
	if result2.GeneratedTokens != result.GeneratedTokens {
		t.Fatalf("token counts differ across identical requests")
	}

	// The engine state cycled ready → busy → ready (existing vocabulary).
	if e.State() != llm.StateReady {
		t.Fatalf("state = %q, want ready after generation", e.State())
	}

	// KV cache: REAL population reported through kv_cache_info.
	kv, err := e.KVCacheInfo(ctx)
	if err != nil {
		t.Fatalf("kv cache info: %v", err)
	}
	if !kv.Allocated {
		t.Fatal("KV cache must be allocated after generation")
	}
	// 2 layers, ctx 64, kv_dim 16 → 2*2*64*16*2 = 8192 bytes.
	if kv.CapacityBytes != 8192 {
		t.Fatalf("KV capacity = %d, want 8192", kv.CapacityBytes)
	}
	// Last request used 12 positions; per-position bytes = 2*layers*kv_dim*2 = 128.
	if kv.UsedPositions != 12 {
		t.Fatalf("KV used positions = %d, want 12", kv.UsedPositions)
	}
	if kv.UsedBytes != 12*128 {
		t.Fatalf("KV used bytes = %d, want %d", kv.UsedBytes, 12*128)
	}

	// Scheduler: REAL execution counts.
	sched, err := e.SchedulerInfo(ctx)
	if err != nil {
		t.Fatalf("scheduler info: %v", err)
	}
	if sched.TotalSubmitted < 2 {
		t.Fatalf("scheduler submitted = %d, want ≥ 2", sched.TotalSubmitted)
	}
	if sched.TotalCompleted < 2 {
		t.Fatalf("scheduler completed = %d, want ≥ 2", sched.TotalCompleted)
	}
	if sched.ActiveRequests != 0 {
		t.Fatalf("scheduler active = %d, want 0 after completion", sched.ActiveRequests)
	}
}

// TestRealCppHostPhase5Cancellation proves REAL cancellation through the
// production boundary: a mid-flight generation on the slow fixture is
// cancelled from Go; the native loop observes it (per token), the final
// frame reports "cancelled", and the engine stays reusable.
func TestRealCppHostPhase5Cancellation(t *testing.T) {
	e := startRealHost(t)
	loadRealFixture(t, e, "tiny-llama-slow.gguf")

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	var mu sync.Mutex
	var chunks int
	sawFirstToken := make(chan struct{})
	var once sync.Once

	var wg sync.WaitGroup
	wg.Add(1)

	var genErr error
	var result GenerationResult

	go func() {
		defer wg.Done()
		result, genErr = e.StreamGeneration(ctx, GenerationRequest{
			RequestID: "cancel-e2e",
			Prompt:    "hello",
			MaxTokens: 200,
			Seed:      7,
		}, func(chunk GenerationChunk) error {
			mu.Lock()
			chunks++
			mu.Unlock()
			once.Do(func() { close(sawFirstToken) })
			return nil
		})
	}()

	// Wait for the first streamed token (decode phase underway), then
	// cancel through the REAL cancel op.
	select {
	case <-sawFirstToken:
	case <-time.After(20 * time.Second):
		t.Error("no first token within 20 s")
	}

	if err := e.Cancel(ctx, "cancel-e2e"); err != nil {
		t.Fatalf("cancel: %v", err)
	}

	wg.Wait()

	if genErr != nil {
		t.Fatalf("cancelled generation returned error: %v", genErr)
	}
	if result.FinishReason != FinishCancelled {
		t.Fatalf("finish reason = %q, want cancelled", result.FinishReason)
	}
	if result.GeneratedTokens == 0 || result.GeneratedTokens >= 200 {
		t.Fatalf("generated tokens = %d, want partial (0 < n < 200)", result.GeneratedTokens)
	}

	// Engine reusable after the cancellation.
	sched, err := e.SchedulerInfo(ctx)
	if err != nil {
		t.Fatalf("scheduler info: %v", err)
	}
	if sched.TotalCancelled < 1 {
		t.Fatalf("scheduler cancelled = %d, want ≥ 1", sched.TotalCancelled)
	}
	if sched.ActiveRequests != 0 {
		t.Fatalf("scheduler active = %d, want 0", sched.ActiveRequests)
	}

	followUp, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "after-cancel",
		Prompt:    "hello",
		MaxTokens: 2,
	}, func(chunk GenerationChunk) error { return nil })
	if err != nil {
		t.Fatalf("generation after cancellation: %v", err)
	}
	// The slow fixture's greedy continuation may legitimately sample EOS
	// as its first token (generated 0, finish eos) — both outcomes prove
	// the engine executed a fresh, unpoisoned request after the cancel.
	switch followUp.FinishReason {
	case FinishLength:
		if followUp.GeneratedTokens != 2 {
			t.Fatalf("follow-up tokens = %d, want 2 (length)", followUp.GeneratedTokens)
		}
	case FinishEOS:
		if followUp.GeneratedTokens != 0 {
			t.Fatalf("follow-up tokens = %d, want 0 (eos)", followUp.GeneratedTokens)
		}
	default:
		t.Fatalf("follow-up finish = %q (poisoned state after cancel?)", followUp.FinishReason)
	}
}

// TestRealCppHostPhase5ContextOverflow proves the context-bound REJECT
// policy (prompt + max_tokens > context → explicit error, no silent
// truncation) and that the engine stays reusable.
func TestRealCppHostPhase5ContextOverflow(t *testing.T) {
	e := startRealHost(t)
	loadRealFixture(t, e, "tiny-llama-f32.gguf")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// ctx=64, prompt=5 tokens → 59 fits exactly, 60 does not.
	_, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "fits",
		Prompt:    "hello",
		MaxTokens: 59,
	}, func(chunk GenerationChunk) error { return nil })
	if err != nil {
		t.Fatalf("fitting request failed: %v", err)
	}

	_, err = e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "overflow",
		Prompt:    "hello",
		MaxTokens: 60,
	}, func(chunk GenerationChunk) error { return nil })
	if err == nil {
		t.Fatal("overflowing request must be rejected")
	}
	if !IsContextExhausted(err) {
		t.Fatalf("error = %v, want a ContextExhaustedError", err)
	}
	if !strings.Contains(err.Error(), "exceeds the model context window") {
		t.Fatalf("error detail = %v", err)
	}

	// Reusable after the rejection.
	result, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "post-reject",
		Prompt:    "hello",
		MaxTokens: 2,
	}, func(chunk GenerationChunk) error { return nil })
	if err != nil {
		t.Fatalf("generation after rejection: %v", err)
	}
	if result.GeneratedTokens != 2 {
		t.Fatalf("tokens = %d, want 2", result.GeneratedTokens)
	}
}

// TestRealCppHostPhase5UnsupportedModel proves the fallback signal: a
// NON-llama model loads fine (Phase 2 semantics) but reports
// generation-capable=0 with the inspectable reason; generation returns
// the explicit unsupported error (the router maps this to llama.cpp).
func TestRealCppHostPhase5UnsupportedModel(t *testing.T) {
	e := startRealHost(t)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// The Phase 4 BPE fixture declares llama metadata but has NO llama
	// tensors beyond a dummy token_embd — generation must be rejected
	// with a clear reason.
	model := writeBPEGGUF(t, t.TempDir(), "bpe.gguf")

	if err := e.LoadModel(ctx, ModelSpec{Path: model}); err != nil {
		t.Fatalf("load: %v", err)
	}

	if e.NativeGenerationCapable() {
		t.Fatal("non-executable model must not report generation capable")
	}

	reason := e.NativeGenerationReason()
	if reason == "" {
		t.Fatal("an inspectable fallback reason is required")
	}

	_, err := e.StreamGeneration(ctx, GenerationRequest{
		RequestID: "unsupported",
		Prompt:    "hello",
		MaxTokens: 4,
	}, func(chunk GenerationChunk) error { return nil })
	if err == nil {
		t.Fatal("generation must fail for an unsupported model")
	}
	if !strings.Contains(err.Error(), "natively executable") &&
		!strings.Contains(err.Error(), "unsupported") {
		t.Fatalf("error = %v, want the unsupported-model signal", err)
	}

	// The llama.cpp fallback stays functional: the model concern itself
	// remains healthy (this engine just cannot generate).
	if e.State() != llm.StateReady {
		t.Fatalf("state = %q, want ready (failed generation is not an engine fault)", e.State())
	}
}

// TestRealCppHostPhase5BackendContract drives the llm.Backend adapter
// against the REAL C++ host end-to-end: LoadModel → Generate /
// StreamGenerate with REAL inference, llm.StreamEvent conversion and
// PerfStats from measured metrics.
func TestRealCppHostPhase5BackendContract(t *testing.T) {
	e := startRealHost(t)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	b := NewBackend(e)

	if b.GenerationCapable() {
		t.Fatal("no model loaded yet — must not be capable")
	}

	if err := b.LoadModel(ctx, llm.ModelSpec{Path: nativeFixturePath("tiny-llama-f32.gguf")}); err != nil {
		t.Fatalf("load: %v", err)
	}

	if !b.GenerationCapable() {
		t.Fatal("real fixture model must be generation capable")
	}

	req := &llm.ChatRequest{
		MaxTokens: 6,
		Messages: []llm.Message{
			{Role: "system", Content: "You are a test."},
			{Role: "user", Content: "hello"},
		},
	}

	// Non-streaming generate.
	resp, err := b.Generate(ctx, req)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if len(resp.Choices) != 1 || resp.Choices[0].Message.Content == "" {
		t.Fatalf("generate response: %+v", resp)
	}
	if resp.Usage.CompletionTokens != 6 {
		t.Fatalf("completion tokens = %d, want 6", resp.Usage.CompletionTokens)
	}

	// Streaming generate with llm.StreamEvent conversion.
	var events []llm.StreamEvent
	perf, err := b.StreamGenerate(ctx, req, func(ev llm.StreamEvent) error {
		events = append(events, ev)
		return nil
	})
	if err != nil {
		t.Fatalf("stream generate: %v", err)
	}
	if len(events) < 2 {
		t.Fatalf("events = %d, want ≥ 2 (content + terminal)", len(events))
	}
	if events[len(events)-1].FinishReason != "length" {
		t.Fatalf("terminal finish = %q", events[len(events)-1].FinishReason)
	}
	if perf.Tokens != 6 {
		t.Fatalf("perf tokens = %d, want 6", perf.Tokens)
	}
	if perf.TTFTMs < 0 || perf.WallMs < 0 {
		t.Fatalf("perf stats negative: %+v", perf)
	}
	if perf.TokensPerSec <= 0 {
		t.Fatalf("perf tokens/sec not measured: %+v", perf)
	}
}
