// test_forward.cpp — Phase 5 transformer forward-pass tests.
//
// NUMERICAL CORRECTNESS (the critical requirement):
//   - the free numerics (rms_norm / rope / softmax / dot / silu) are
//     verified against ANALYTIC hand-computed values;
//   - the staged values (embedding row, rmsnorm output, q/k/v projections)
//     are compared against the INDEPENDENT Python reference
//     (tests/reference/make_fixture.py, numpy — not the C++ code);
//   - the FULL forward pass (2 layers × GQA attention × fp16 KV cache ×
//     SwiGLU × logits) is compared against the Python reference logits
//     for the fixture prompt — any deviation in attention, GQA mapping,
//     causal masking, RoPE or residuals shows up here;
//   - greedy sampling from the real logits must pick the reference
//     argmax token.
//
// The fixture and reference are generated by
//   python3 tests/reference/make_fixture.py
// and committed (deterministic).

#include "shtn/engine.h"
#include "shtn/types.h"

#include "forward.h"
#include "fp16.h"
#include "llama.h"
#include "tensor.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

static int failures = 0;

#define CHECK(cond)                                                        \
    do {                                                                   \
        if (!(cond)) {                                                     \
            std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__,    \
                         #cond);                                           \
            ++failures;                                                    \
        }                                                                   \
    } while (0)

// --- flat reference loader -----------------------------------------------------

using namespace shtn;

static std::unordered_map<std::string, std::vector<double>> load_ref(
    const std::string& path) {
    std::unordered_map<std::string, std::vector<double>> out;
    std::ifstream f(path);
    if (!f) {
        std::fprintf(stderr, "cannot open reference %s\n", path.c_str());
        return out;
    }
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream iss(line);
        std::string name;
        iss >> name;
        std::vector<double> vals;
        double v;
        while (iss >> v) {
            vals.push_back(v);
        }
        out[name] = vals;
    }
    return out;
}

static bool close_enough(const std::vector<double>& ref, const float* got,
                         uint32_t n, double tol, const char* what) {
    bool ok = true;
    for (uint32_t i = 0; i < n; ++i) {
        const double r = ref[i];
        const double g = got[i];
        const double diff = std::fabs(r - g);
        const double scale = std::max(1.0, std::fabs(r));
        if (diff > tol * scale) {
            std::fprintf(stderr,
                         "MISMATCH %s[%u]: ref=%.9g got=%.9g (diff %.3g)\n",
                         what, i, r, g, diff);
            ok = false;
            if (!ok) break;
        }
    }
    if (!ok) {
        ++failures;
    }
    return ok;
}

int main() {
    const std::string fixtures = SHTN_FIXTURES_DIR;

    const auto ref = load_ref(fixtures + "/tiny-llama-ref.txt");
    CHECK(!ref.empty());

    const auto& hyper_ref = ref.at("hyper");
    const auto& prompt_ref = ref.at("prompt");

    // --- unit: rms_norm against a hand-computed reference -----------------
    {
        // x = [3, 4]; mean(x^2) = 12.5; scale = 1/sqrt(12.5 + 0.5)
        const float x[2] = {3.0f, 4.0f};
        const float w[2] = {1.0f, 0.5f};
        float out[2];
        fwd::rms_norm(x, w, 2, 0.5, out);
        const double scale = 1.0 / std::sqrt(12.5 + 0.5);
        CHECK(std::fabs(out[0] - 3.0 * scale) < 1e-6);
        CHECK(std::fabs(out[1] - 4.0 * 0.5 * scale) < 1e-6);
    }

    // --- unit: rope against analytic rotation ------------------------------
    {
        // head_dim = 4, half = 2. freqs: base^0 = 1, base^(-0.5).
        std::vector<float> freqs;
        fwd::rope_freqs(4, 10000.0, freqs);
        CHECK(freqs.size() == 2);
        CHECK(std::fabs(freqs[0] - 1.0) < 1e-6);
        CHECK(std::fabs(freqs[1] - std::pow(10000.0, -0.5)) < 1e-6);

        // head = [1, 2, 3, 4], pos = 1.
        float head[4] = {1.0f, 2.0f, 3.0f, 4.0f};
        fwd::rope(head, 4, 1, freqs.data());

        const float th0 = 1.0f * freqs[0];
        const float th1 = 1.0f * freqs[1];
        const float c0 = std::cos(th0), s0 = std::sin(th0);
        const float c1 = std::cos(th1), s1 = std::sin(th1);
        // x[j]' = x[j]*cos - x[j+half]*sin; x[j+half]' = x[j]*sin + x[j+half]*cos
        CHECK(std::fabs(head[0] - (1.0f * c0 - 3.0f * s0)) < 1e-6);
        CHECK(std::fabs(head[1] - (2.0f * c1 - 4.0f * s1)) < 1e-6);
        CHECK(std::fabs(head[2] - (1.0f * s0 + 3.0f * c0)) < 1e-6);
        CHECK(std::fabs(head[3] - (2.0f * s1 + 4.0f * c1)) < 1e-6);
    }

    // --- unit: softmax / dot / silu ------------------------------------------
    {
        float v[3] = {1.0f, 2.0f, 3.0f};
        fwd::softmax_inplace(v, 3);
        const double e1 = std::exp(-2.0), e2 = std::exp(-1.0), e3 = 1.0;
        const double sum = e1 + e2 + e3;
        CHECK(std::fabs(v[0] - e1 / sum) < 1e-6);
        CHECK(std::fabs(v[1] - e2 / sum) < 1e-6);
        CHECK(std::fabs(v[2] - e3 / sum) < 1e-6);

        const float a[3] = {1.0f, 2.0f, 3.0f};
        const float b[3] = {4.0f, -5.0f, 6.0f};
        CHECK(std::fabs(fwd::dot(a, b, 3) - (4.0 - 10.0 + 18.0)) < 1e-6);

        CHECK(std::fabs(fwd::silu(0.0f)) < 1e-7);
        CHECK(std::fabs(fwd::silu(1.0f) - 0.7310586) < 1e-6);
    }

    // --- load the fixture through the REAL engine ----------------------------
    shtn_engine* engine = nullptr;
    {
        shtn_engine_options opts{};
        opts.abi_version = SHTN_ABI_VERSION;
        opts.reserved = 0;
        CHECK(shtn_engine_create(&opts, &engine) == SHTN_OK);
        CHECK(engine != nullptr);

        shtn_model_load_options lopts{};
        lopts.context_length = 0;
        lopts.reserved = 0;
        CHECK(shtn_engine_load_model(
                  engine, (fixtures + "/tiny-llama-f32.gguf").c_str(),
                  &lopts) == SHTN_OK);

        shtn_model_info mi{};
        CHECK(shtn_engine_model_info(engine, &mi) == SHTN_OK);
        CHECK(mi.generation_capable == 1); // the fixture is llama + F32
        CHECK(mi.generation_reason[0] == '\0');
    }

    // --- stage comparisons against the Python reference --------------------
    {
        // Get the model's weights view through the model concern (the same
        // access the forward pass uses).
        // (The engine internals are private; the stage comparisons run
        // through a fresh parse of the same file — identical code path as
        // Model::load.)
        gguf::MappedFile mapping;
        std::string err;
        CHECK(mapping.open(fixtures + "/tiny-llama-f32.gguf", err));
        gguf::GgufHeader header;
        CHECK(gguf::parse_header(mapping, header, err));

        llama::Hyper h;
        CHECK(llama::derive(header.metadata, h, err));
        CHECK(llama::validate(header, h, err));
        CHECK(h.emb == 32 && h.layers == 2 && h.heads == 4 && h.kv_heads == 2);
        CHECK(h.head_dim == 8 && h.ffn == 64 && h.context == 64);
        CHECK(std::fabs(h.rms_eps - 1e-5) < 1e-12);
        CHECK(std::fabs(h.rope_freq_base - 10000.0) < 1e-6);
        CHECK(!h.output_tied);
        CHECK(h.vocab_size == 32);

        tensor::Weights weights(header);
        weights.bind_data(mapping.data(), mapping.size());

        tensor::Weights* w = &weights;

        // 1. Embedding of prompt[0].
        {
            tensor::RowBuf row;
            CHECK(w->row_f32(llama::tensor_token_embd(),
                             static_cast<uint64_t>(prompt_ref[0]), h.emb, 0,
                             row, err) == SHTN_OK);
            close_enough(ref.at("embedding_t0"), row.data(), h.emb, 1e-5,
                         "embedding_t0");
        }

        // 2. rms_norm(embedding, attn_norm[0]).
        {
            tensor::RowBuf row;
            CHECK(w->row_f32(llama::tensor_token_embd(),
                             static_cast<uint64_t>(prompt_ref[0]), h.emb, 0,
                             row, err) == SHTN_OK);

            tensor::RowBuf norm_w;
            CHECK(w->vec_f32(llama::tensor_attn_norm(0), h.emb, norm_w, err) ==
                  SHTN_OK);

            std::vector<float> out(h.emb);
            fwd::rms_norm(row.data(), norm_w.data(), h.emb, h.rms_eps,
                          out.data());
            close_enough(ref.at("rmsnorm_after_emb"), out.data(), h.emb, 1e-5,
                         "rmsnorm_after_emb");
        }

        // 3. q/k/v projections of the normalized embedding.
        {
            tensor::RowBuf row;
            CHECK(w->row_f32(llama::tensor_token_embd(),
                             static_cast<uint64_t>(prompt_ref[0]), h.emb, 0,
                             row, err) == SHTN_OK);
            tensor::RowBuf norm_w;
            CHECK(w->vec_f32(llama::tensor_attn_norm(0), h.emb, norm_w, err) ==
                  SHTN_OK);
            std::vector<float> xb(h.emb);
            fwd::rms_norm(row.data(), norm_w.data(), h.emb, h.rms_eps,
                          xb.data());

            // Reproduce the engine's matvec: out[i] = dot(row_i, xb).
            tensor::RowBuf wrow;
            std::vector<float> q(h.attn_out_dim);
            for (uint32_t i = 0; i < h.attn_out_dim; ++i) {
                CHECK(w->row_f32(llama::tensor_attn_q(0), i, h.emb, 0, wrow,
                                 err) == SHTN_OK);
                q[i] = fwd::dot(wrow.data(), xb.data(), h.emb);
            }
            close_enough(ref.at("q_proj_l0_p0"), q.data(), h.attn_out_dim,
                         1e-5, "q_proj_l0_p0");

            std::vector<float> k(h.kv_dim);
            for (uint32_t i = 0; i < h.kv_dim; ++i) {
                CHECK(w->row_f32(llama::tensor_attn_k(0), i, h.emb, 0, wrow,
                                 err) == SHTN_OK);
                k[i] = fwd::dot(wrow.data(), xb.data(), h.emb);
            }
            close_enough(ref.at("k_proj_l0_p0"), k.data(), h.kv_dim, 1e-5,
                         "k_proj_l0_p0");

            std::vector<float> v(h.kv_dim);
            for (uint32_t i = 0; i < h.kv_dim; ++i) {
                CHECK(w->row_f32(llama::tensor_attn_v(0), i, h.emb, 0, wrow,
                                 err) == SHTN_OK);
                v[i] = fwd::dot(wrow.data(), xb.data(), h.emb);
            }
            close_enough(ref.at("v_proj_l0_p0"), v.data(), h.kv_dim, 1e-5,
                         "v_proj_l0_p0");
        }
    }

    // --- FULL FORWARD: logits vs the Python reference ----------------------
    {
        // Drive the engine's own Forward through one generate call with
        // max_tokens=1 and greedy sampling: the FIRST sampled token must
        // be the reference argmax. (This exercises prefill + logits +
        // sampler over REAL logits through the public ABI.)
        shtn_generation_options opts{};
        const char* prompt = "hello"; // the fixture prompt text
        opts.request_id = "forward-test";
        opts.prompt = prompt;
        opts.prompt_len = 5;
        opts.max_tokens = 1;
        opts.temperature = 0.0f; // greedy
        opts.top_k = 0;
        opts.top_p = 1.0f;
        opts.repetition_penalty = 1.0f;
        opts.repeat_last_n = 64;
        opts.seed = 0;
        opts.reserved = 0;

        std::string got_text;
        uint32_t got_token = 0xFFFFFFFFu;

        auto emit = [](void* user, const shtn_generation_chunk* chunk) -> int32_t {
            auto* sink = static_cast<std::pair<std::string, uint32_t>*>(user);
            if (chunk == nullptr) return 0;
            sink->first.append(chunk->text, chunk->text_len);
            if (!chunk->final) {
                sink->second = chunk->token_id;
            }
            return 0;
        };

        std::pair<std::string, uint32_t> sink;
        shtn_generation_result result{};
        char detail[256] = {0};
        const int32_t rc = shtn_engine_generate(engine, &opts, emit, &sink,
                                                &result, detail);
        CHECK(rc == SHTN_OK);
        CHECK(std::string(result.finish_reason) == SHTN_FINISH_LENGTH);

        // The first (and only) sampled token must match the reference
        // argmax — REAL logits through the REAL forward pass.
        const double want = ref.at("argmax_token")[0];
        CHECK(sink.second != 0xFFFFFFFFu);
        if (sink.second != 0xFFFFFFFFu) {
            CHECK(static_cast<double>(sink.second) == want);
        }

        // Metrics: measured values present (1 prompt-window, 1 token).
        CHECK(result.metrics.prompt_tokens > 0);
        CHECK(result.metrics.generated_tokens == 1);
        CHECK(result.metrics.kv_positions_used >= 4);
        CHECK(result.metrics.total_seconds > 0.0);
    }

    // --- direct Forward logits comparison (unit-level, full pass) ----------
    {
        // Parse + bind like Model::load, then run Forward::token over the
        // reference prompt and compare the FINAL logits with Python.
        gguf::MappedFile mapping;
        std::string err;
        CHECK(mapping.open(fixtures + "/tiny-llama-f32.gguf", err));
        gguf::GgufHeader header;
        CHECK(gguf::parse_header(mapping, header, err));

        llama::Hyper h;
        CHECK(llama::derive(header.metadata, h, err));
        CHECK(llama::validate(header, h, err));

        tensor::Weights weights(header);
        weights.bind_data(mapping.data(), mapping.size());

        fwd::Forward fwd;
        CHECK(fwd.init(&weights, h, 0, err) == SHTN_OK);

        // KV cache is really allocated with fp16-exact accounting.
        const kv::Stats ks = fwd.cache().stats();
        CHECK(ks.allocated);
        CHECK(ks.capacity_bytes ==
              2ull * h.layers * h.context * h.kv_dim * 2);
        CHECK(ks.quantization == "f16");

        std::vector<float> logits(h.vocab_size);
        for (size_t i = 0; i < prompt_ref.size(); ++i) {
            const int32_t rc = fwd.token(
                static_cast<uint32_t>(prompt_ref[i]), i, logits.data(), err);
            CHECK(rc == SHTN_OK);
            if (rc != SHTN_OK) break;
        }

        // The KV cache holds prompt positions now.
        CHECK(fwd.cache().used_positions() == prompt_ref.size());
        CHECK(fwd.cache().stats().used_bytes ==
              prompt_ref.size() * fwd.cache().bytes_per_position());

        // Final logits vs the independent Python reference (fp16 KV +
        // accumulation-order differences → tolerance 1e-3 relative).
        close_enough(ref.at("logits_final"), logits.data(), h.vocab_size,
                     1e-3, "logits_final");

        // Greedy argmax over the native logits == reference argmax.
        uint32_t am = 0;
        for (uint32_t v = 1; v < h.vocab_size; ++v) {
            if (logits[v] > logits[am]) am = v;
        }
        CHECK(static_cast<double>(am) == ref.at("argmax_token")[0]);
    }

    shtn_engine_destroy(engine);

    if (failures > 0) {
        std::fprintf(stderr, "test_forward: %d failure(s)\n", failures);
        return 1;
    }

    std::printf("test_forward: all checks passed\n");
    return 0;
}
