#!/usr/bin/env bash
# Build + package SHEYTAN-Local-Agent v1.1.1 (Zeta) — Windows native desktop app
# on the Wails v3 shell with the Node/Vite (React) frontend.
#
# DUAL OUTPUT:
#   1. /home/z/my-project/download/sheytan-local-agent-1.1.1.zip
#      The ready-to-run portable app: exe (icon + Parsa Tak-signed version
#      info + DPI manifest), optional bundled llama.cpp engine, docs, worklog.
#
#   2. /home/z/my-project/download/sheytan-local-agent-1.1.1-github.zip
#      The GitHub-ready SOURCE tree: every line of code, no .exe, no engine
#      binaries, no generated .syso — plus .gitignore and a CI workflow so
#      `git init && push` produces a building repository whose Actions
#      rebuild the exe automatically.
#
# v1.1.1Z (Zeta) — the CI-repair + legacy-cleanup release:
#   - The Linux CI job now installs the packages Wails v3 actually links
#     (libgtk-4-dev + libwebkitgtk-6.0-dev + libsoup-3.0-dev). The v1.1.0
#     workflow installed the Wails v2 era GTK3/WebKit2 packages, so every
#     Linux build failed at "Go tests" with "Package gtk4 was not found".
#   - CI pins the Node 24 toolchain via actions/setup-node for the
#     React/Vite frontend and keeps Go pinned to 1.26.
#   - The Windows CI build regenerates the .syso resources (brand icon,
#     Parsa Tak signature, DPI-aware manifest) and links with
#     -H=windowsgui; the .bat launcher ships inside the portable ZIP.
#   - The versioned legacy sources are RETIRED: cmd/stress_v08.go ...
#     cmd/stress_v110.go and the versioned e2e scripts are gone. The
#     stress suite is the Zeta chaos suite (cmd/stress.go +
#     cmd/stress_zeta.go).
#   - web/static is regenerated by the committed Node/Vite build (the
#     stale pre-SettingsPanel bundle that was committed is gone).
#   - The application remains SIGNED UNDER THE NAME PARSA TAK (exe
#     CompanyName, About dialog, SIGNATURE file in both zips).
set -euo pipefail

cd "$(dirname "$0")/.."

VERSION="1.1.1"
APP_NAME="sheytan-local-agent"
STAGE_DIR="dist-stage/$APP_NAME"
GH_STAGE_DIR="dist-stage/$APP_NAME-github"
DIST_DIR="/home/z/my-project/download"
ENGINE_SRC="/home/z/my-project/engine-dl/vulkan"
ENGINE_TAG="b10642"

# Clean + recreate stage
rm -rf "$STAGE_DIR" "$GH_STAGE_DIR"
mkdir -p "$STAGE_DIR"

# The embedded frontend must exist in the tree (it is committed; CI
# regenerates it from src/ on every push).
if [ ! -f web/static/index.html ]; then
  echo "!! web/static/index.html missing — run 'npm run build' first."
  exit 1
fi

# Regenerate LICENSE from the in-app brand text (they can never drift).
echo ">> Regenerating LICENSE from brand.LicenseText..."
go run scripts/gen-license.go

# Generate the SIGNATURE block (signed under: Parsa Tak).
echo ">> Generating SIGNATURE (signed by Parsa Tak)..."
go run scripts/gen-signature.go "$VERSION"

# Run stress tests first — don't ship if any test fails.
# scripts/stress-main is a headless entry point: the root main package wires
# the Wails desktop shell (which on Linux needs GTK/WebKit cgo headers),
# while stress-main wires a no-op default so the suite runs anywhere.
echo ">> Building Linux stress-test binary..."
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/sheytan-stress ./scripts/stress-main
echo ">> Running stress suite..."
if ! SHEYTAN_DATA_DIR=/tmp/sheytan-stress-root /tmp/sheytan-stress stress 2>&1 | tail -3 | grep -q "0 fail"; then
  echo "!! Stress tests failed; aborting."
  exit 1
fi
rm -rf /tmp/sheytan-stress-root
echo ">> All stress tests pass."

echo ">> Running unit tests (Linux, no CGO)..."
if ! CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -tags headless \
    ./internal/sessions ./internal/memory ./internal/chunking ./internal/recall \
    ./internal/tools ./internal/vision ./internal/termshell ./internal/resources \
    ./internal/continuum ./internal/native ./internal/releasegate \
    ./internal/lab ./internal/llm ./internal/research ./internal/aicontext \
    > /tmp/unittest.log 2>&1; then
  cat /tmp/unittest.log
  echo "!! Unit tests failed; aborting."
  exit 1
fi
echo ">> All unit tests pass."

# Windows cross-compile: Wails v3 on Windows is cgo-free, so a plain
# CGO_ENABLED=0 cross build produces the release exe. No mingw needed.
export GOOS=windows
export GOARCH=amd64
export CGO_ENABLED=0

# Regenerate the Windows resource object — the app icon (brand flame,
# multi-size), version info (SIGNED BY PARSAT TAK as CompanyName + the
# signature line in Comments + LegalTrademarks), and the PerMonitorV2
# DPI-awareness manifest. gen-syso embeds a committed PNG, so it runs on
# any host OS.
echo ">> Generating Windows resources (icon + Parsa Tak signature + DPI manifest)..."
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go run ./scripts/gen-syso
if [ ! -f rsrc_windows_amd64.syso ]; then
  echo "!! rsrc_windows_amd64.syso was not generated."
  exit 1
fi

echo ">> Building Windows .exe (Wails + Node UI)..."
go build -ldflags="-s -w -H=windowsgui" -o "$STAGE_DIR/$APP_NAME.exe" .

# Sanity: the exe must carry the brand strings AND the signature.
if ! grep -q "SHEYTAN" "$STAGE_DIR/$APP_NAME.exe" 2>/dev/null; then
  echo "!! exe looks wrong (brand strings missing)"
  exit 1
fi
if ! python3 -c "
data = open('$STAGE_DIR/$APP_NAME.exe','rb').read()
assert 'Parsa Tak'.encode('utf-16-le') in data, 'signature missing'
assert '$VERSION'.encode('utf-16-le') in data, 'version missing'
"; then
  echo "!! exe signature/version metadata verification failed"
  exit 1
fi
echo ">> exe verified: brand + Parsa Tak signature + v$VERSION present."

echo ">> Vet (windows target, full tree — mirrors CI)..."
go vet ./... > /dev/null

# Copy launcher + docs + license + AI instruction file + worklog + signature
cp sheytan-local-agent.bat "$STAGE_DIR/"
cp README.md "$STAGE_DIR/"
cp LICENSE "$STAGE_DIR/"
cp SIGNATURE "$STAGE_DIR/"
cp internal/aicontext/AI-CONTEXT.md "$STAGE_DIR/AI-CONTEXT.md"
# The worklog ships in the zip so the next agent (or developer)
# picks up EXACTLY where this session ended. The repository worklog is
# the canonical project history; the session worklog (if present) is a
# fallback.
if [ -f worklog.md ]; then
  cp worklog.md "$STAGE_DIR/worklog.md"
elif [ -f /home/z/my-project/worklog.md ]; then
  cp /home/z/my-project/worklog.md "$STAGE_DIR/worklog.md"
fi

# --- optionally bundle the llama.cpp engine (Vulkan + CPU backends) ---
# The app also auto-downloads the engine on first run (internal/installer),
# so a missing engine folder is a warning, not a hard error.
if [ -d "$ENGINE_SRC" ]; then
  echo ">> Bundling llama.cpp engine ($ENGINE_TAG, Vulkan + CPU) into bin/..."
  mkdir -p "$STAGE_DIR/bin"
  ENGINE_FILES=(
    llama-server.exe
    llama-server-impl.dll
    llama-common.dll
    llama.dll
    ggml.dll
    ggml-base.dll
    ggml-rpc.dll
    ggml-vulkan.dll
    libomp.dll
    mtmd.dll
    LICENSE-LLVM-OpenMP
  )
  # every CPU variant dll
  for f in "$ENGINE_SRC"/ggml-cpu-*.dll; do
    ENGINE_FILES+=("$(basename "$f")")
  done
  engine_ok=1
  for f in "${ENGINE_FILES[@]}"; do
    if [ -f "$ENGINE_SRC/$f" ]; then
      cp "$ENGINE_SRC/$f" "$STAGE_DIR/bin/"
    else
      echo "   engine file missing (skipped): $f"
      engine_ok=0
    fi
  done
  if [ "$engine_ok" -eq 1 ]; then
    echo ">> Engine bundled: $(ls "$STAGE_DIR/bin" | wc -l) files, $(du -sh "$STAGE_DIR/bin" | cut -f1)."
  else
    echo ">> Engine partially bundled; the app auto-downloads the rest on first run."
  fi
else
  echo ">> Engine source $ENGINE_SRC not found — the app auto-downloads it on first run."
fi

# Pre-create the portable folder skeleton so users see where things go.
mkdir -p "$STAGE_DIR/models" "$STAGE_DIR/workspace" "$STAGE_DIR/charts"

# --- ZIP 1: the full portable app ---
ZIP="$DIST_DIR/$APP_NAME-$VERSION.zip"
mkdir -p "$DIST_DIR"
rm -f "$ZIP"
( cd dist-stage && zip -r -q "$ZIP" "$APP_NAME" )
echo ""
echo ">> ZIP 1 (full app): $ZIP"
ls -lh "$ZIP"

# --- GITHUB SOURCE TREE (with build-integrity gates) ---
# The gate tradition began in v1.1.0's predecessors: unanchored .gitignore
# patterns once matched internal/sessions + internal/sandbox at any depth,
# so git silently refused to commit them and the release shipped broken.
# internal/releasegate still fails CI if a pattern ever swallows source.
echo ">> Staging GitHub source tree..."
mkdir -p "$GH_STAGE_DIR"
rsync -a --delete \
  --exclude 'dist-stage/' \
  --exclude 'build/' \
  --exclude '*.exe' \
  --exclude '*.syso' \
  --exclude '*.zip' \
  --exclude '/local-agent' \
  --exclude '/build.log' \
  --exclude '/build1.log' \
  --exclude '.git/' \
  --exclude 'build/shots/' \
  --exclude 'scripts/build-and-zip*.sh.bak' \
  ./ "$GH_STAGE_DIR/"
# Source zips carry docs + signature too.
cp SIGNATURE "$GH_STAGE_DIR/SIGNATURE" 2>/dev/null || true
if [ -f worklog.md ]; then
  cp worklog.md "$GH_STAGE_DIR/worklog.md"
fi

# GATE 1 — the critical packages must be physically present in the staged tree.
for critical in internal/sessions/sessions.go internal/sandbox/sandbox.go internal/releasegate/releasegate_test.go internal/desktop/desktop.go; do
  if [ ! -f "$GH_STAGE_DIR/$critical" ]; then
    echo "!! CRITICAL SOURCE MISSING from the staged GitHub tree: $critical"
    exit 1
  fi
done
echo ">> GATE 1 passed: internal/sessions + internal/sandbox + internal/releasegate + internal/desktop staged."

# GATE 2 — git itself must neither ignore nor refuse to track the critical
# packages in the tree we ship (mirrors internal/releasegate; this is the
# exact user-side failure mode of v1.0.10: the zips were complete, but the
# user's `git add` silently dropped the packages because the .gitignore
# that shipped INSIDE the zip matched them).
# NOTE: no `grep -q` pipes here — under `set -o pipefail`, grep's early
# exit SIGPIPEs git and turns a PASS into a false FAIL.
if command -v git >/dev/null 2>&1; then
  gate2_ok=1
  ( cd "$GH_STAGE_DIR" && git init -q ) || gate2_ok=0
  if [ "$gate2_ok" -eq 1 ]; then
    # (a) a scratch `git add -A` dry-run must LIST the critical files…
    listed=$( cd "$GH_STAGE_DIR" && git add -A -n 2>/dev/null || true )
    if [ -z "$listed" ]; then
      echo "!! GATE 2 FAILED: git add dry-run listed nothing in the staged tree"
      gate2_ok=0
    fi
    if [ "$gate2_ok" -eq 1 ]; then
      for critical in internal/sessions/sessions.go internal/sandbox/sandbox.go internal/releasegate/releasegate_test.go internal/desktop/desktop.go; do
        case "$listed" in
          *"$critical"*) ;; # git would track it — good
          *)
            echo "!! GATE 2 FAILED: git would NOT track $critical in the shipped tree"
            gate2_ok=0
            break
            ;;
        esac
        # (b) …and check-ignore must not flag it as ignored.
        if ( cd "$GH_STAGE_DIR" && git check-ignore -q -- "$critical" ); then
          echo "!! GATE 2 FAILED: the shipped .gitignore ignores $critical"
          gate2_ok=0
          break
        fi
      done
    fi
  fi
  rm -rf "$GH_STAGE_DIR/.git"
  if [ "$gate2_ok" -ne 1 ]; then
    echo "   (this is the exact v1.0.9/v1.0.10 bug — anchor runtime dirs with a leading '/')"
    exit 1
  fi
  echo ">> GATE 2 passed: git tracks and does not ignore the critical packages."
fi

# GATE 3 — the staged tree must COMPILE on its own.
echo ">> GATE 3: compiling the GitHub source tree (windows/amd64, cgo-free — CI parity)..."
# Wails v3 on Windows needs no cgo, so this mirrors the GitHub Actions
# runner exactly and needs no GTK/X11/mingw environment on the build host.
if ! ( cd "$GH_STAGE_DIR" && \
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 \
    go build ./... 2> /tmp/gh-compile.log ); then
  cat /tmp/gh-compile.log
  echo "!! The GitHub source tree does not compile — refusing to ship."
  exit 1
fi
echo ">> GATE 3 passed: the source tree builds clean (windows/amd64, all packages)."

# GATE 4 — the sealed zip itself must contain the critical packages.
# (No grep -q pipes: under pipefail, grep's early exit SIGPIPEs unzip and
# a successful match would look like a failure.)
GH_ZIP="$DIST_DIR/$APP_NAME-$VERSION-github.zip"
rm -f "$GH_ZIP"
( cd dist-stage && zip -r -q "$GH_ZIP" "$APP_NAME-github" )
zip_listing=$( unzip -l "$GH_ZIP" 2>/dev/null || true )
for critical in "internal/sessions/sessions.go" "internal/sandbox/sandbox.go" "internal/releasegate/releasegate_test.go" "internal/desktop/desktop.go"; do
  case "$zip_listing" in
    *"$critical"*) ;; # present in the sealed zip — good
    *)
      echo "!! GATE 4 FAILED: $critical is not inside the sealed GitHub zip."
      exit 1
      ;;
  esac
done
echo ">> GATE 4 passed: the sealed zip carries the critical packages."
echo ""
echo ">> ZIP 2 (GitHub source): $GH_ZIP"
ls -lh "$GH_ZIP"

# Guard: the GitHub zip must NOT contain any exe/dll/syso (or the
# extensionless Linux build binary).
if unzip -l "$GH_ZIP" | grep -Ei '\.(exe|dll|syso)$|/local-agent$' | grep -q .; then
  echo "!! GitHub zip contains binaries — refusing to ship:"
  unzip -l "$GH_ZIP" | grep -Ei '\.(exe|dll|syso)$|/local-agent$'
  exit 1
fi
echo ">> GitHub zip verified: pure source, zero binaries."

echo ""
echo ">> Done. Outputs:"
ls -lh "$ZIP" "$GH_ZIP" | awk '{print "   " $NF " (" $5 ")"}'
